[2023-10-14T02:50:58.274+0000] {taskinstance.py:1147} INFO - Dependencies not met for <TaskInstance: dataframe_lab1.save_data scheduled__2023-10-07T00:00:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2023-10-14T02:50:58.287+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
[2023-10-14T03:36:04.950+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dataframe_lab1.save_data scheduled__2023-10-07T00:00:00+00:00 [queued]>
[2023-10-14T03:36:04.957+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dataframe_lab1.save_data scheduled__2023-10-07T00:00:00+00:00 [queued]>
[2023-10-14T03:36:04.957+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-14T03:36:04.969+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): save_data> on 2023-10-07 00:00:00+00:00
[2023-10-14T03:36:04.973+0000] {standard_task_runner.py:57} INFO - Started process 278 to run task
[2023-10-14T03:36:04.975+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dataframe_lab1', 'save_data', 'scheduled__2023-10-07T00:00:00+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/titanic.py', '--cfg-path', '/tmp/tmph820ze4x']
[2023-10-14T03:36:04.978+0000] {standard_task_runner.py:85} INFO - Job 137: Subtask save_data
[2023-10-14T03:36:05.013+0000] {task_command.py:415} INFO - Running <TaskInstance: dataframe_lab1.save_data scheduled__2023-10-07T00:00:00+00:00 [running]> on host 89ffa62682cc
[2023-10-14T03:36:05.179+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dataframe_lab1' AIRFLOW_CTX_TASK_ID='save_data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-07T00:00:00+00:00'
[2023-10-14T03:36:05.228+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-14T03:36:05.234+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=dataframe_lab1, task_id=save_data, execution_date=20231007T000000, start_date=20231014T033604, end_date=20231014T033605
[2023-10-14T03:36:05.268+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-14T03:36:05.279+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
